### ISSUE TITLE
As a church leader, I'd like Project Zoe to support multitenancy 

### ISSUE THREAD

**Issue by kakoma** [kanzucodefoundation/project-zoe-server#73]
Project Zoe currently supports a single tenant. As a church leader, I'd like to be able to create an account for my church as well. 

## Implementation notes
- There are 3 options for the database architecture: 
  1. **Separate databases, separate schemas:** Each tenant would have its own database. In the Postgres server, we'd have a separate database created for each tenant. One example of Open Source software that uses this pattern is [Mifos](https://github.com/openMF/web-app) 
  2. **Shared Database, separate schema:** All the tenants use the same database but have separate tables. In this scenario, tables are usually prefixed in a certain way to be able to identify which ones belong to which tenant. One example of Open Source software that uses this pattern is WordPress for its multi-tenant setup 
  3. **Shared Database, Shared Scheme:** All tenants use the same database and the same tables. A tenant ID is used in the tables to identify which data belongs to which tenant. 
- I recommend the second option - Shared database, separate schema. See https://youtu.be/Yryn1C2isUk?t=56 for a summary of the pros and cons, and this https://www.youtube.com/watch?v=LnHAGEdH21U for a more detailed walk-through of the pros and cons. While **Separate databases, separate schemas** has lots of pros, the cost makes it untenable for a free solution. Also, as WordPress shows, the second option (with further tweaks to the overall architecture) can be scaled to support thousands of tenants. WordPress's multi-tenancy setup at https://wordpress.com/ uses this option. 

## Acceptance criteria [To be modified]
- Modify the database schema to support multiple tenants
- Modify the backend to support getting the appropriate data from the database based on the request
- Modify the client to specify the tenant while requesting for data

**NOTE**: This should be changed into an epic and broken down into client and server-side issues

**Comment by ekastimo** [comment]
Thanks, @kakoma, two questions
Are we also looking at subdomains?
What would the onboarding process look like for a new church?

**Comment by kakoma** [comment]
I envision us hosting the setup at projectzoecms.org and each tenant being accessible at church1.projectzoecms.org, church2.projectzoecms.org, church3.projectzoecms.org. Basically, when a church is done signing up [there would need to be a card capturing the sign up process],  the relevant tables are created for it and it is setup and becomes accessible at worshipharvest.projectzoecms.org, where the church name is Worship Harvest. 

Then, for those with a technical team and interested in accessing the setup from their own domain, they would add a CNAME record to their domain setup pointing from rms.worshipharvest.org [where their domain is worshipharvest.org] to worshipharvest.projectzoecms.org. 

So onboarding would come down to filling in a form where you share some information and then we'd do all the heavy-lifting and give you a sub-domain when everything is done. @ekastimo

**Comment by kakoma** [comment]
This was added using a schema-based approach

> Shared Database, separate schema: All the tenants use the same database but have separate tables. In this scenario, tables are usually prefixed in a certain way to be able to identify which ones belong to which tenant. One example of Open Source software that uses this pattern is WordPress for its multi-tenant setup
