### ISSUE TITLE
As a user, I'd like to see parts of the application to which they have no rights.

### ISSUE THREAD

**Issue by androidcode33** [kanzucodefoundation/project-zoe-server#80]
**Acceptance criteria**
- Users without appropriate report rights were able to submit reports. 
- Edit permission should give both read/write access to any part of the system while view rights should be only for the read.

**Comment by androidcode33** [comment]
@MariamNaiga add the PR link on here.

**Comment by MariamNaiga** [comment]
[Frontend PR](https://github.com/kanzucodefoundation/project-zoe-client/pull/72)

**Comment by androidcode33** [comment]
@ekastimo this is ready

**Comment by kakoma** [comment]
This was merged
